### ISSUE TITLE
テキストボックスの文字数制限を行う

### ISSUE THREAD

**Issue by riantkb** [yamashita1224/ITSPFuG202_client#34]
https://console.firebase.google.com/project/fug202-e1f3d/crashlytics/app/android:jp.ac.titech.itpro.sdl.itspfug202/issues/5bd97740f8b88c2963f1dee0?time=last-seven-days&sessionId=5BD97B940035000178661533DD180421_DNE_0_v2
https://console.firebase.google.com/project/fug202-e1f3d/crashlytics/app/android:jp.ac.titech.itpro.sdl.itspfug202/issues/5bd97f1ff8b88c2963f2c14c?time=last-seven-days&sessionId=5BD980F502B8000112091533DD180421_DNE_0_v2

> こっちについては再現ができて、自分の場合は検索窓に 240KB のテキストを入れて検索すると発生しました（あまり真剣に対応しなくても良さそうだけど検索窓に文字数制限をかけるのが丸いかな）

`android:maxLength="100"` みたいな感じに1行付け足すだけで解決しそうな気持ちがある

**Comment by matsu-ITSP** [comment]
#37
