### ISSUE TITLE
営業時間表示まわりのコードが汚い

### ISSUE THREAD

**Issue by matsu-ITSP** [yamashita1224/ITSPFuG202_client#6]
enumなのに配列の順番で代入を行ったり、使わないstringが残ったまま(どうしようもなさそう)になっていたりしてよろしくない。restaurantクラスの変数名も分かりにくい。

**Comment by riantkb** [comment]
#22 と一緒になんとかしたいね

**Comment by riantkb** [comment]
まぁマシになったのでとりあえず閉じます
